# See config.example.yml for documentation.
name: main
object_base: orig/G4QE01
object: sys/main.dol

map: orig/G4QE01/files/MarioSoccerD.MAP

hash: 376d699c99b6b0949abe1b4ceccefdef7828d2b5

symbols: config/G4QE01/symbols.txt
splits: config/G4QE01/splits.txt

# mw_comment_version: 8 # GC Linker 1.2.5
# symbols_known: true # Very fast analysis
# fill_gaps: false # Alignments known
# quick_analysis: true # Faster reruns after full analysis
mw_comment_version: 11 # GC 2.7 linker
