# See config.example.yml for documentation.
name: main
object_base: orig/G4QE01
object: sys/main.dol

# map: orig/G4QE01/files/MarioSoccerZ.MAP

hash: 376d699c99b6b0949abe1b4ceccefdef7828d2b5

symbols: config/G4QE01/symbols.txt
splits: config/G4QE01/splits.txt

mw_comment_version: 10 # GC Linker 2.6
symbols_known: true # Very fast analysis
fill_gaps: false # Alignments known

write_asm: true
ldscript_template: config/G4QE01/ldscript.tpl
